spring:
  profiles:
    active: local, spy

  application:
    name: tech_chnl

logging:
  level:
    root: info


--- # spy
decorator:
  datasource:
    p6spy:
      enable-logging: true


--- # local
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kcredit
    username: kcredit
    #password: kcredit
    password: ENC(sQIqV+ZbbIsiwwmpji3/Pw==)


--- # test
spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kcredit
    username: kcredit
    password: kcredit


--- # real
spring:
  config:
    activate:
      on-profile: real

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kcredit
    username: kcredit
    password: kcredit
